### ISSUE TITLE
Not working with mongodb

### ISSUE THREAD

**Issue by sirmadboy** [paulomcnally/loopback-example-multitenant#1]
I have changed the datasources to mongodb, but it cant point to exact tenant. for example when i tried to access http://localhost:4000/demo2/tweets, instead of returning the data from db "demo2", it still return the data from db "demo". same as i when accessed http://localhost:4000/demo1/tweets.
the point is it's still not redirect to the appropriate tenant. do I did something wrong?

ps: sorry for my bad english..:)

**Comment by paulomcnally** [comment]
This example is for postgreSQL.

I don't have an example for MongoDB.

Work in process.
