### ISSUE TITLE
Unable to get correct DataSource

### ISSUE THREAD

**Issue by hendra-pratama** [paulomcnally/loopback-example-multitenant#3]
Hi McNally,

I am Tama.
I am interested in trying what you've done in this example. Your code is working well.
Then, I managed to reproduce your code in mine.
So far it is successfully getting the correct json datasource file;  i.e. datasources.newtenant.json
And set this part:
        app.dataSources[dataSource].adapter.settings = dataSourceObj[dataSource];
        app.dataSources[dataSource].adapter.clientConfig = dataSourceObj[dataSource];
        app.dataSources[dataSource].settings = dataSourceObj[dataSource];
        app.dataSources[dataSource].connector.settings = dataSourceObj[dataSource];
        app.dataSources[dataSource].connector.clientConfig = dataSourceObj[dataSource];

But my models are still connected to its initial datasource.
Did you experience this case when developing this example? can you please let me know what I could be missing?
Thank you for your kindness of helping me.

**Comment by venkatrjv2** [comment]
Me Too..

**Comment by hendra-pratama** [comment]
Hi @venkatrjv2 ,
I found that the issue was caused by the version, you need to downgrade the version.
This versions work for me:

```
"cors": "^2.8.1",
"loopback": "^2.8.0",
"loopback-boot": "^2.4.0",
"loopback-component-explorer": "^2.4.0",
"loopback-connector-postgresql": "^1.5.0",
"strong-error-handler": "^1.0.1",
"errorhandler": "^1.1.1",
"loopback-datasource-juggler": "^2.7.0"
```

Please let me know whether or not it works for you. Thanks you

**Comment by venkatrjv2** [comment]
I figured it out , Now its working Fine...

Problem is when you get requests from different tenants. 
**Example :**
tenant 1
tenant 2
tenant 3

The last Tenant 3 datasource is updating to Tenant 1 and tenant 2 ... as because node js is asynchronous..
What to do in that situation ..
